application: datalogcompiler
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css 
- url: /js
  static_dir: js
- url: /.*
  script: datalogcompiler.app
